# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etxazpi/vscodeprojects/fleeceExtractor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etxazpi/vscodeprojects/fleeceExtractor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etxazpi/vscodeprojects/fleeceExtractor/CMakeFiles /home/etxazpi/vscodeprojects/fleeceExtractor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etxazpi/vscodeprojects/fleeceExtractor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named defleece

# Build rule for target.
defleece: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 defleece
.PHONY : defleece

# fast build rule for target.
defleece/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/defleece.dir/build.make CMakeFiles/defleece.dir/build
.PHONY : defleece/fast

#=============================================================================
# Target rules for targets named FleeceObjects

# Build rule for target.
FleeceObjects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FleeceObjects
.PHONY : FleeceObjects

# fast build rule for target.
FleeceObjects/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/FleeceObjects.dir/build.make vendor/fleece/CMakeFiles/FleeceObjects.dir/build
.PHONY : FleeceObjects/fast

#=============================================================================
# Target rules for targets named Fleece

# Build rule for target.
Fleece: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fleece
.PHONY : Fleece

# fast build rule for target.
Fleece/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/Fleece.dir/build.make vendor/fleece/CMakeFiles/Fleece.dir/build
.PHONY : Fleece/fast

#=============================================================================
# Target rules for targets named FleeceStatic

# Build rule for target.
FleeceStatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FleeceStatic
.PHONY : FleeceStatic

# fast build rule for target.
FleeceStatic/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/FleeceStatic.dir/build.make vendor/fleece/CMakeFiles/FleeceStatic.dir/build
.PHONY : FleeceStatic/fast

#=============================================================================
# Target rules for targets named FleeceBase

# Build rule for target.
FleeceBase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FleeceBase
.PHONY : FleeceBase

# fast build rule for target.
FleeceBase/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/FleeceBase.dir/build.make vendor/fleece/CMakeFiles/FleeceBase.dir/build
.PHONY : FleeceBase/fast

#=============================================================================
# Target rules for targets named fleeceTool

# Build rule for target.
fleeceTool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fleeceTool
.PHONY : fleeceTool

# fast build rule for target.
fleeceTool/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/fleeceTool.dir/build.make vendor/fleece/CMakeFiles/fleeceTool.dir/build
.PHONY : fleeceTool/fast

#=============================================================================
# Target rules for targets named FleeceTests

# Build rule for target.
FleeceTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FleeceTests
.PHONY : FleeceTests

# fast build rule for target.
FleeceTests/fast:
	$(MAKE) $(MAKESILENT) -f vendor/fleece/CMakeFiles/FleeceTests.dir/build.make vendor/fleece/CMakeFiles/FleeceTests.dir/build
.PHONY : FleeceTests/fast

#=============================================================================
# Target rules for targets named sqlite3

# Build rule for target.
sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite3
.PHONY : sqlite3

# fast build rule for target.
sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f vendor/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/build.make vendor/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/build
.PHONY : sqlite3/fast

defleece.o: defleece.cpp.o
.PHONY : defleece.o

# target to build an object file
defleece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/defleece.dir/build.make CMakeFiles/defleece.dir/defleece.cpp.o
.PHONY : defleece.cpp.o

defleece.i: defleece.cpp.i
.PHONY : defleece.i

# target to preprocess a source file
defleece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/defleece.dir/build.make CMakeFiles/defleece.dir/defleece.cpp.i
.PHONY : defleece.cpp.i

defleece.s: defleece.cpp.s
.PHONY : defleece.s

# target to generate assembly for a file
defleece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/defleece.dir/build.make CMakeFiles/defleece.dir/defleece.cpp.s
.PHONY : defleece.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Fleece"
	@echo "... FleeceBase"
	@echo "... FleeceObjects"
	@echo "... FleeceStatic"
	@echo "... FleeceTests"
	@echo "... defleece"
	@echo "... fleeceTool"
	@echo "... sqlite3"
	@echo "... defleece.o"
	@echo "... defleece.i"
	@echo "... defleece.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

