name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ubuntu Latest"
            os: ubuntu-latest
            artifact: "defleece"
          - name: "Windows Latest"
            os: windows-latest
            artifact: "buid/Debug/defleece.exe"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
        
    - name: Create build environment
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure CMake
      if: runner.os != 'Windows'
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{github.workspace}}/build
      run: cmake .. -A x64
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . 
      
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ${{matrix.config.artifact}}
      
    
